project:
  type: website

website:
  title: "Unified Branding"
  
  bread-crumbs: true
  
  repo-url: https://github.com/posit-dev/brand-yml/
  repo-actions: [issue, source]

  announcement: 
    content: |
      This is a work in progress and documentation may be out of date.
      Please drop by [`#brand-yaml`](https://positpbc.slack.com/archives/C07KVQBUCCF)
      with questions or feedback.
    type: warning
    dismissable: false

  navbar:
    left:
      - text: Overview
        href: index.qmd
      - text: brand.yml
        href: brand/index.qmd
      - text: "Examples"
        href: examples/index.qmd
      - text: Packages
        menu:
          - text: Python
            href: pkg/py/index.qmd

  sidebar:
    - id: brand-yml
      contents:
        - text: Design Goals
          href: index.qmd
        - brand/open-questions.qmd
        - text: "----"
        - text: Structure
          href: brand/index.qmd
        - section: Brand Elements
          contents:
          - brand/meta.qmd
          - brand/logo.qmd
          - brand/color.qmd
          - brand/typography.qmd
          - brand/defaults.qmd
    - id: examples-brands
      title: Example Brand Guidelines
      contents: "examples/brand-guidelines/*/index.qmd"

format:
  html:
    theme: [bootstrap, "posit-theme.scss"]
    toc: true

lightbox: auto

metadata-files:
  - _sidebar-python.yml
  # - _sidebar-r.yml

quartodoc:
  package: brand_yaml
  style: pkgdown
  dir: pkg/py
  sidebar: _sidebar-python.yml
  title: brand_yaml Python Package Reference
  out_index: api.qmd
  dynamic: true
  render_interlinks: true
  sections:
    - title: Read or create a brand
      desc: Read a `_brand.yml` file or create an instance of a Brand.
      contents:
        - Brand
        - read_brand_yaml
    - title: Brand Components
      desc: Individual brand components.
      contents:
        - meta.BrandMeta
        - logo.BrandLogo
        - color.BrandColor
        - typography.BrandTypography

interlinks:
  fast: true
  sources:
    pydantic:
      url: https://docs.pydantic.dev/latest/
    python:
      url: https://docs.python.org/3/

editor:
  render-on-save: true

