project:
  type: website
  preview: 
    port: 4243

website:
  title: "Unified Branding"
  
  bread-crumbs: true
  
  repo-url: https://github.com/posit-dev/brand-yml/
  repo-actions: [issue, source]

  announcement: 
    content: |
      This is a work in progress and documentation may be out of date.
      Please drop by [`#brand-yaml`](https://positpbc.slack.com/archives/C07KVQBUCCF)
      with questions or feedback.
    type: warning
    dismissable: false

  navbar:
    left:
      - text: Overview
        href: index.qmd
      - text: brand.yml
        href: brand/index.qmd
      - text: "Examples"
        href: examples/index.qmd
      - text: Packages
        menu:
          - text: Python
            href: pkg/py/index.qmd

  sidebar:
    - id: brand-yml
      contents:
        - text: Design Goals
          href: index.qmd
        - brand/open-questions.qmd
        - text: "----"
        - text: Structure
          href: brand/index.qmd
        - section: Brand Elements
          contents:
          - brand/meta.qmd
          - brand/logo.qmd
          - brand/color.qmd
          - brand/typography.qmd
          - brand/defaults.qmd
    - id: examples-brands
      title: Example Brand Guidelines
      contents: "examples/brand-guidelines/*/index.qmd"

format:
  html:
    theme: [bootstrap, "posit-theme.scss"]
    toc: true

lightbox: auto

metadata-files:
  - _sidebar-python.yml
  # - _sidebar-r.yml

quartodoc:
  package: brand_yaml
  renderer: 
    style: _renderer.py
  dir: pkg/py
  sidebar: _sidebar-python.yml
  title: brand_yaml Python Package Reference
  out_index: api.qmd
  dynamic: true
  render_interlinks: true
  rewrite_all_pages: true
  sections:
    - title: Read or create a brand
      desc: Read a `_brand.yml` file or create an instance of a Brand.
      contents:
        - Brand
        - read_brand_yaml
    - title: Brand Components
      desc: Individual brand components.
      options:
        signature_name: relative
        include_imports: false
        include_inherited: false
        include_attributes: true
        include_classes: true
        include_functions: true
      contents:
        - kind: page
          path: meta
          summary:
            name: Metadata
          contents: 
            - BrandMeta
            - meta.BrandMetaName
            - meta.BrandMetaLink
        - kind: page
          path: logo
          summary:
            name: Logos and Images
          contents: 
            - BrandLogo
            - BrandLightDark
            - FileLocation
            - FileLocationLocal
            - FileLocationUrl
        - kind: page
          path: color
          summary:
            name: Color Palette and Theme
          contents:
            - BrandColor
        - kind: page
          path: typography
          summary:
            name: Typography
          contents:
            - BrandTypography
            # - typography.BrandTypographyFontFamily
            - name: typography
              members:
                - BrandTypographyFontSource
                - BrandTypographyFontFiles
                - BrandTypographyFontGoogle
                - BrandTypographyFontBunny
                - BrandTypographyGoogleFontsApi
                - BrandTypographyGoogleFontsWeightRange

interlinks:
  fast: true
  sources:
    pydantic:
      url: https://docs.pydantic.dev/latest/
    python:
      url: https://docs.python.org/3/

editor:
  render-on-save: true
