project:
  type: website
  preview:
    port: 4243
  resources:
    # TODO: remove when logo is supported by brand meta
    - "logos/**/*.png"
    - "logos/**/*.svg"
    - objects.txt
  post-render:
    - mkdir -p _site/schema
    - cp ../schema/brand.schema.yml _site/schema
    - cp ../schema/brand.schema.json _site/schema

website:
  title: "brand.yml"
  site-url: https://posit-dev.github.io/brand-yml/
  description: Unified branding with a simple YAML file

  bread-crumbs: true

  repo-url: https://github.com/posit-dev/brand-yml/
  repo-actions: [issue, edit]
  repo-subdir: docs

  navbar:
    left:
      - text: About
        href: index.qmd
      - text: Structure
        menu:
          - text: Overview
            href: brand/index.qmd
          - text: "---"
          - text: "Brand Elements"
          - brand/meta.qmd
          - brand/logo.qmd
          - brand/color.qmd
          - brand/typography.qmd
          - brand/defaults.qmd
      - text: "Inspiration"
        href: inspiration/index.qmd
      - articles/index.qmd
      - text: Python
        href: pkg/py/index.qmd
    tools:
      - icon: github
        menu:
          - text: Source code
            href:  https://github.com/posit-dev/brand-yml
          - text: Ask a question
            href:  https://github.com/posit-dev/brand-yml/discussions
          - text: Report a bug
            href:  https://github.com/posit-dev/brand-yml/issues/new

  sidebar:
    - id: brand-yml
      style: docked
      contents:
        - text: About
          href: index.qmd
        - text: Structure
          href: brand/index.qmd
        - section: Brand Elements
          contents:
          - brand/meta.qmd
          - brand/logo.qmd
          - brand/color.qmd
          - brand/typography.qmd
          - brand/defaults.qmd
    - id: inspiration-brands
      title: Example Brand Guidelines
      contents: "inspiration/brand-guidelines/*/index.qmd"

format:
  html:
    theme: [brand, "brand-yml-theme.scss"]
    toc: true

lightbox: auto

filters:
  - preview-colour

preview-colour:
  code: true

metadata-files:
  - _sidebar-python.yml
  # - _sidebar-r.yml

quartodoc:
  package: brand_yml
  renderer:
    style: _renderer.py
  dir: pkg/py
  sidebar: _sidebar-python.yml
  title: brand_yml Python Package Reference
  out_index: api.qmd
  dynamic: true
  render_interlinks: true
  rewrite_all_pages: true
  sections:
    - title: Reference
      desc: Read a `_brand.yml` file or create an instance of a Brand.
      options:
        signature_name: relative
        include_imports: false
        include_inherited: false
        include_attributes: true
        include_classes: true
        include_functions: true
      contents:
        - Brand
        - kind: page
          path: meta
          summary:
            name: Metadata
          contents:
            - BrandMeta
            - meta.BrandMetaName
            - meta.BrandMetaLink
        - kind: page
          path: logo
          summary:
            name: Logos and Images
          contents:
            - BrandLogo
            - BrandLogoResource
            - BrandLightDark
            - FileLocation
            - FileLocationLocal
            - FileLocationUrl
            - file.FileLocationLocalOrUrlType
        - kind: page
          path: color
          summary:
            name: Color Palette and Theme
          contents:
            - BrandColor
        - kind: page
          path: typography
          summary:
            name: Typography
          contents:
            - BrandTypography
            - name: typography
              members:
                - BrandTypographyFontFamily
                - BrandTypographyFontSource
                - BrandTypographyFontFiles
                - BrandTypographyFontGoogle
                - BrandTypographyFontBunny
                - BrandTypographyGoogleFontsApi
                - BrandTypographyGoogleFontsWeightRange
                - BrandTypographyBase
                - BrandTypographyHeadings
                - BrandTypographyMonospace
                - BrandTypographyMonospaceInline
                - BrandTypographyMonospaceBlock
                - BrandTypographyLink
        - kind: page
          path: utilities
          summary:
            name: Utilities
          contents:
            - find_project_brand_yml

interlinks:
  fast: true
  sources:
    pydantic:
      url: https://docs.pydantic.dev/latest/
    python:
      url: https://docs.python.org/3/

editor:
  render-on-save: true
  markdown:
    canonical: true
    wrap: sentence
